<h1>Numpy WB</h1>

In [4]:
import numpy as np # --> Numpy import ettik 

In [6]:
height = [1.73,1.68,1.71,1.89,1.79]

In [7]:
print(height)

[1.73, 1.68, 1.71, 1.89, 1.79]


In [8]:
np_height = np.array(height)

In [9]:
weight = [65.4,59.2,63.6,88.4,68.7]

In [10]:
print(weight)

[65.4, 59.2, 63.6, 88.4, 68.7]


In [11]:
np_weight = np.array(weight)

In [12]:
bmi = np_weight / np_height **2

In [13]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

--Numpy import etmeden önce, python yukarıdaki değerlerin dizileri tek bir değermiş gibi algılamıyor. Numpy import ettikten sonra, bu dizileri tek bir değermiş gibi algılıyor.

In [14]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [16]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

--Python yukarıdaki kodu, iç içe birleştirerek yazdı. Aynı işlemi numpy ile yaptığımız zaman sonuç, herbir değerin, karşıdaki değerle toplanması ile sonuçlanacak.

In [17]:
numpy_array + numpy_array

array([2, 4, 6])

--Python Slice
a[start:stop:step]# items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array

In [20]:
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [22]:
height[1:] #Birinci indeksten itibaren tümü.

[1.68, 1.71, 1.89, 1.79]

In [23]:
height[1:3] #Birinci ve üçüncü indeks aralığı ancak üçüncü dahil değil.

[1.68, 1.71]

In [25]:
height[:3] #Üçüncü indeksten sonrası çıkıyor.

[1.73, 1.68, 1.71]

In [28]:
height[::-1] #Arrayi tersine çeviriyor, sonuncu indeks başa geliyor.

[1.79, 1.89, 1.71, 1.68, 1.73]

<h2>2D Numpy Arrays </h2>

In [29]:
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],[65.4,59.2,63.6,88.4,68.7]])

In [30]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [34]:
np_2d.shape #2 satır, 5 sütun. Shape komutu, yapının 
#bize nasıl göründüğü ile alakalı bilgi verir.

(2, 5)

In [67]:
np_2d[0][2]

1.71

-Numpy'da 2 boyutlu arrayleri liste içinde liste olarak düşünebiliriz. Shape komutunu yazdığımızda, satır sayısı, aslında ilgili arrayin kaç adet indeksten oluştuğunu söylüyor.
-Yukarıdaki kod bloğunda, np_2d arrayinin 0. indeksini baz aldık (yani aslında birinci shape, ardından birinci shape listesinin de 2.indeksini çağırdık.

In [68]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

-Yukarıda, ilk kısımda herhangi bir sayı yazmadık ve listenin tamamını çağırmış olduk. Daha sonrasında her iki listede de 1'den 3'e kadar olan indeksleri çağırmış olduk. (Son indeks hiçbir zaman dahil edilmiyor.)

In [69]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [120]:
np_1d = np_2d[:,1]

In [121]:
np_1d

array([ 1.68, 59.2 ])

In [122]:
avg = np.mean(np_2d[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_2d[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_2d[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
# Correct way to use np.corrcoef for two columns
corr = np.corrcoef(np_2d[:,0], np_2d[:,1])
print("Correlation: " + str(corr))

Average: 33.565000000000005
Median: 33.565000000000005
Standard Deviation: 31.835000000000004
Correlation: [[1. 1.]
 [1. 1.]]
